### ISSUE TITLE
chromedriver package needs to be dependency of this project

### ISSUE THREAD

**Issue by christian-bromann** [atti187/wdio-chromedriver-service#12]
Hey,

thanks for making this service for WebdriverIO. I was just recently using it and was confused why I had to extra install the Chromedriver NPM package. How about we make this as a dependency to this project so everyone who is downloading the service is good to go.

Cheers
Christian

**Comment by atti187** [comment]
This was changed due to #7. I guess some people wanted better control over which version of Chromedriver being used. What's your take?

**Comment by christian-bromann** [comment]
Got it. Well makes sense even though I don't understand why someone would want to use an older Chromedriver version. However since Chromedriver is not installed automatically it should be documented that this needs to be installed extra.
