### ISSUE TITLE
Different port the 9515

### ISSUE THREAD

**Issue by tasmo** [atti187/wdio-chromedriver-service#13]
The service runs nicely when I use the default port in the config.

As soon as I change the port to any other value the tests fail with:
```dtrace
ERROR: connect ECONNREFUSED 127.0.0.1:10101
chrome
```

**Comment by atti187** [comment]
In wdio.conf, you need to specify the port where the service, i.e. ChromeDriver in this case, is running and ChromeDriver is started by wdio-chromedriver-service on port 9515 by default, so just keep it to 9515.

If you were running with another service, you'd have to change the port to whatever port that service is running on, e.g. 4444 for Selenium. It's how Webdriver.io communicates with the services, not the port your application under test exposes.

**Comment by tasmo** [comment]
That is what I've expected. For CI testing I want to have multiple instances of Chromedriver running at the same host. That for I need to run the services at different ports.

How do I tell Chromedriver to run on a different port if not setting the port in the wdio.conf ?

**Comment by atti187** [comment]
ChromeDriver can be started on different ports, see https://helpmanual.io/help/chromedriver/

You should be able to use a chromeDriverArgs-property in your wdio.conf-file, see https://github.com/atti187/wdio-chromedriver-service/blob/master/lib/launcher.js.

// wdio.conf.js
export.config = {
  port: '9515',
  path: '/',
  // ...
  services: ['chromedriver'],
  chromeDriverArgs: ['--verbose', '--port', '9999'],
  // ...
};

Give it a try!

**Comment by avistramer** [comment]
Came across this issue as well. The above suggestion is right on, but the syntax is slightly off. If you wanted to use chromedriver on port 9999:

```
// wdio.conf.js
export.config = {
port: '9999',
path: '/',
// ...
services: ['chromedriver'],
chromeDriverArgs: ['--verbose', '--port=9999'],
// ...
};
```

It's probably worth adding this to the README since it is a somewhat common requirement.

**Comment by tasmo** [comment]
@avistramer @atti187 Just had to remove `'--verbose'` to get it working. Single arguments might be without the `--` like in browser args.

**Comment by GokulManivannan** [comment]
I tried the same steps but it's not working. Anyone can help us to fix it?

**Comment by christian-bromann** [comment]
@GokulManivannan this is a very old thread. The service has a port option you can use to define a specific port for Chromedriver. Please provide more information what is not working.
