### ISSUE TITLE
Update Chromedriver

### ISSUE THREAD

**Issue by LaiaPR** [atti187/wdio-chromedriver-service#14]
Hi!

I am having an issue with chromedriver very similar to this one https://github.com/SeleniumHQ/docker-selenium/issues/566 and it seems that should be fixed for newer versions of Chromedriver.

It will be helpful to update the Chromedriver dependency. 

See that, trying with `yarn upgrade` , I am getting this warning:

`warning " > wdio-chromedriver-service@0.1.3" has unmet peer dependency "chromedriver@^2.31.0".`

**Comment by atti187** [comment]
What's the version of chromedriver you're using in your own project? See #12

**Comment by LaiaPR** [comment]
I do not have an explicit Chromedriver dependency in my package.json , only this:

`"wdio-chromedriver-service": "~0.1.1",`

Also, I am using https://github.com/webdriverio/cucumber-boilerplate to execute my tests and Yarn as a dependency manager.

**Comment by atti187** [comment]
Then you need to add chromdriver as a separate dependency to your package.json.
