### ISSUE TITLE
Unable to start wdio runner

### ISSUE THREAD

**Issue by callmekatootie** [atti187/wdio-chromedriver-service#19]
I am not sure where to report this issue - in wdio's runner or here. Please let me know if this is an issue with webdriverio and not this service.

With version 5 of webdriver io, I used the CLI and installed chromedriver service. I then started the runner but then ran into an error:

`ERROR wdio-local-runner:utils: TypeError: Service is not a constructor`

After debugging, I found out that runner is expecting a service to be exported by this module, as can be seen in this [statement](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/utils.js#L114). But this module does not export anything.

**Comment by diachedelic** [comment]
Is this package actually compatible with wdio@5 or should I be using `@wdio/selenium-standalone-service` for locally running chrome?

**Comment by atti187** [comment]
I've missed that wdio 5 was out. I guess this service needs some update, according to @callmekatootie  's comment above. It might even be that wdio 5 picks the right driver and starts chromedriver automatically, in which case this service is no longer needed. @christian-bromann - can you please comment?

**Comment by fedecia** [comment]
wdio v5 doesn't start chromedriver automatically, we need to modify your service to make it work with v5. I know there's been a conversion about doing that here:

https://gitter.im/webdriverio/v5?at=5c2e54668dafa715c73875d1

**Comment by atti187** [comment]
Ok - I'll have a look at it, but feel free to create a PR if it's taking too long!

**Comment by atti187** [comment]
@callmekatootie @diachedelic @fedecia - would you care to try this out? I noticed that `path: '/'` needed to be `path: ''` on a Windows. Will check if osx in indifferent...

**Comment by fedecia** [comment]
@atti187 it works fine. thanks!

you're right about the path for windows, right now I have to do this in the config:
`    port: 9515,
    path: process.platform === 'win32' ? '' : '/',`
