### ISSUE TITLE
Will there be support for chromedriver@^74.0.0?

### ISSUE THREAD

**Issue by joehuanguf** [atti187/wdio-chromedriver-service#24]
Currently the service is throwing an "unmet peer dependency" error, because we have chromedriver 74.0.0 instead of ^2.45.0

**Comment by atti187** [comment]
Shouldn't be hard to fix - unless there are incompatible changes in there... Weird how they use semver though, just following the Chrome version number. Incrementing MAJOR (73, 74, 75 etc) should mean incompatible API changes... I guess the peer dependency must accept any future version, like ">2.45"?

**Comment by atti187** [comment]
Was already handled by #23. Must have missed that - now merged and published!
