### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by kevinmcdonnell** [atti187/wdio-chromedriver-service#3]
Can you release a new version with the support for chromedriver arguments?

Thanks

**Comment by atti187** [comment]
Hi, I'm out traveling and don't have access to my computer. I'll get it done when I'm back in 2-3 weeks, unless I find some other way.

**Comment by kevinmcdonnell** [comment]
shame, I'm having issues with selenium server and want to replace it sooner

ill probably fork the repo, thanks for the project tho!

**Comment by atti187** [comment]
I hear you...see if I can fire up a quick AWS instance and release from there.

**Comment by atti187** [comment]
Ok - done! Love AWS.
