### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by erwinheitzman** [atti187/wdio-chromedriver-service#31]
Hi!

You have released v6 but it's having some issues.
The way Babel is setup in this project requires source-map-support to be a dependency
It seems that NPM releases are being made manually
So without NODE_ENV set in the environment
Therefor the sourcemap is not stripped out the compiled code
Because of this the WebdriverIO team uses https://www.npmjs.com/package/np for releasing packages to release
I would advice to do the same so that the releases cannot go wrong.

Could you please re-release v6 with the NODE_ENV set because currently we get:
```
Error: Couldn't initialise "wdio-chromedriver-service".
Error: Cannot find module 'source-map-support/register'
```

**Comment by atti187** [comment]
Fixed - please try https://www.npmjs.com/package/wdio-chromedriver-service/v/6.0.1

**Comment by erwinheitzman** [comment]
works! thank you ;)
