### ISSUE TITLE
broken argument passing in v6

### ISSUE THREAD

**Issue by k03mad** [atti187/wdio-chromedriver-service#32]
Hello,

https://github.com/atti187/wdio-chromedriver-service/commit/e6ffa820a3cee2092c1e085574657480ae939fa4#diff-4ccffbfc1d25b27efb9c2697f07065dcL18
Since this change it is no longer possible to pass args to ChromeDriver.

For example, I've used in v5 `chromeDriverArgs: ['--silent']` to remove any ChromeDriver messages from console.

**Comment by atti187** [comment]
@erwinheitzman - any reason why this type of configuration fell out? I guess it has to do with https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html#service-configurations, but could easily be added again, right?

**Comment by erwinheitzman** [comment]
@atti187 he is using the v6 with v5 which are incompatible. since the readme only shows the current way of configuring, we could add a link to v5 and v6 for example.

@k03mad simply use the latest v5 version of this service if you are using version 5 of webdriverio. when you'll upgrade to v6 then the new way of configuring the service will apply.

**Comment by k03mad** [comment]
@erwinheitzman I think there might have been a little bit of a misunderstanding here.

I wan't to use `wdio-chromedriver-service v6`, but in this version it is no longer possible to pass args to ChromeDriver, except of some default: https://github.com/atti187/wdio-chromedriver-service#options

In `wdio-chromedriver-service v5` there was `chromeDriverArgs` array in options where you can pass extra args. In `v6` this feature was removed.

May be I'm doing something wrong, how to pass `--silent` argument to ChromeDriver in `wdio-chromedriver-service v6`?

**Comment by erwinheitzman** [comment]
@k03mad if you are using webdriverio v5 then you cannot use v6 of this service, you will have to use v5.

if however you are using webdriverio v6 then you are able to use v6 of this service and you can configure it like described here: https://github.com/atti187/wdio-chromedriver-service/blob/master/README.md#configuration

I hope this helps and if you still have some questions be sure to let me know :)

**Comment by erwinheitzman** [comment]
Regarding the chromeDriverArgs you can pass these like you previously did but instead of putting it all in the root of the wdio config you put it in the service object like so:
```
services: [
    ['chromedriver', { chromeDriverArgs: ['--silient'] }],
]
```

**Comment by erwinheitzman** [comment]
@atti187 is there any way for me to contact you on behalf of the webdriverio team? :)

**Comment by k03mad** [comment]
> Regarding the chromeDriverArgs you can pass these like you previously did but instead of putting it all in the root of the wdio config you put it in the service object like so:
> 
> ```
> services: [
>     ['chromedriver', { chromeDriverArgs: ['--silient'] }],
> ]
> ```

%)

This is not working, because chromeDriverArgs option broken since v6 update of current service.

chromeDriverArgs is empty array: https://github.com/atti187/wdio-chromedriver-service/blob/master/src/launcher.js#L29
Then you push some defaults: https://github.com/atti187/wdio-chromedriver-service/blob/master/src/launcher.js#L33
The you start chrome: https://github.com/atti187/wdio-chromedriver-service/blob/master/src/launcher.js#L42

I can't add extra args to chromeDriverArgs array!

**Comment by k03mad** [comment]
It's broken functional, I just try to explain, but I can't, I think because of my english... :)

Ok, no problem, I'm stay with `wdio-chromedriver-service v5` + `wdio v6` (YES, it's working, and any custom ChromeDriver arg working which I wan't to pass).

**Comment by erwinheitzman** [comment]
@k03mad you are right! Seems like I forgot to write a test for that.

I can push a fix soon for this :)

**Comment by k03mad** [comment]
Hooray! Thank you :)

**Comment by erwinheitzman** [comment]
@k03mad a PR with a fix has been created so you can probably test it soon

**Comment by k03mad** [comment]
@erwinheitzman it works, thank you!
