### ISSUE TITLE
No longer works with chrome 85?

### ISSUE THREAD

**Issue by jam2z9** [atti187/wdio-chromedriver-service#41]
I'd been using this package to run WDIO with chrome v83 previously, but now that chrome 85 is out and installed on machine it no longer works. 

It tells me to update chromedriver to v85.

**Comment by estefrare** [comment]
Hi @jam2z9! I have the same problem. What did you do to fix it?
My solution was to uninstall chrome and install chrome 83 on my machine.

**Comment by lupoalejandro** [comment]
We fix it change the version to the `package.json`
