### ISSUE TITLE
Update to WebdriverIO v7

### ISSUE THREAD

**Issue by christian-bromann** [atti187/wdio-chromedriver-service#44]
Currently this package can't be used with the latest version of WebdriverIO v7, due to this line: https://github.com/atti187/wdio-chromedriver-service/blob/master/package.json#L36. The hooks haven't changed much (only the Cucumber ones). It would be great if we could update.

**Comment by atti187** [comment]
Check out https://www.npmjs.com/package/wdio-chromedriver-service/v/7.0.0... ping me if it's not working!

**Comment by christian-bromann** [comment]
Thanks for the quick fix 🙏
