### ISSUE TITLE
Handle verbose logging

### ISSUE THREAD

**Issue by radiovisual** [atti187/wdio-chromedriver-service#6]
Is there a way to pass the `--verbose` flag to ChromeDriver via this service?

In [the documentation]( https://sites.google.com/a/chromium.org/chromedriver/logging#all-languages), we only get this example:

```
chromedriver.exe --verbose --log-path=chromedriver.log
```

Is there a way to pass this flag to ChromeDriver via this service?

Thanks!

**Comment by radiovisual** [comment]
I tried using both of these as options in my `wdio.conf.js`:

```js
chromeDriverArgs: ['verbose'],
```

and 

```js
chromeDriverArgs: ['--verbose'],
```

but neither of them seemed to work.

**Comment by atti187** [comment]
I used 

`chromeDriverArgs: ['--verbose'],`

and

`chromeDriverLogs: 'ChromeDriver.txt',`

and did get debug output in the file.

**Comment by radiovisual** [comment]
did you get verbose output? Because I can confirm that I am getting output to the custom chromeDriver log file, but I am only getting standard output.

I have:

```
chromeDriverArgs: ['--verbose'],
chromeDriverLogs: './chromedriver/logs',
```
and I always get the exact same output (shown in my comment above).

My versions:

- `wdio`: `4.6.2`
- `wdio-chromedriver-service`: `0.1.0`
- `ChromeDriver`: `2.31.488774`

**Comment by atti187** [comment]
$ cat ChromeDriver.txt
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 9515
Only local connections are allowed.
[2.539][INFO]: COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "handlesAlerts": true,
      "javascriptEnabled": true,
      "locationContextEnabled": true,
      "loggingPrefs": {
         "browser": "ALL",
         "driver": "ALL"
      },
      "requestOrigins": {
         "name": "webdriverio",
         "url": "http://webdriver.io",
         "version": "4.6.2"
      },
      "rotatable": true
...
...
...
