### ISSUE TITLE
Chromedriver should be a peerDependency

### ISSUE THREAD

**Issue by fatso83** [atti187/wdio-chromedriver-service#7]
Right now the Chromedriver seems bound to this package. I think it would be more appropriate to let people decide which version they would like to have installed, and rather set limits on the semantic versioning in `peerDependencies: { 'chromedriver': '2.x' } }`.

**Comment by albertogasparin** [comment]
@atti187 I just want to flag that you published this change as a patch release, however a minor should have been more appropriate as it ends up breaking test jobs.

**Comment by atti187** [comment]
My bad - my test project had chromedriver as a dependency already, so it went unnoticed.
