### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:9515

### ISSUE THREAD

**Issue by albertogasparin** [atti187/wdio-chromedriver-service#9]
Often, just right starting the tests, I get this error:

```
ERROR: connect ECONNREFUSED 127.0.0.1:9515
chrome
    at new RuntimeError (.../node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (.../node_modules/webdriverio/build/lib/utils/RequestHandler.js:327:43)
    at self.callback (.../node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (.../node_modules/webdriverio/node_modules/request/request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
```

I'm running my tests with `wdio` with these settings:

```js
capabilities: [
    {
      browserName: 'chrome',
      maxInstances: 4,
      chromeOptions: {
        args: [
              '--headless',
              // fix headless chrome gpu bug
              '--disable-gpu',
              // force win size as wdio call might not work
              '--window-size=1280,750',
            ],
      },
    },
  ],
  sync: true,
  logLevel: 'silent',
  coloredLogs: true,
  connectionRetryCount: 3,
  services: ['chromedriver', 'visual-regression'],
  path: '/',
  port: '9515',
```

I've also tried adding `--ignore-certificate-errors` flag, but it didn't help. Running the command again may succeed, but sometime I have to re-run it 3-4 times before success.
On top of that, headless chrome instances are not closed when that error happens. The first time I noticed it, I had hundreds running...

**Comment by mgamaHapyak** [comment]
Hi. I am also using the chromedriver service but I do have this parameters on the wdio.conf.js file: port: 9515,
    path: '/',

That works for me, so maybe that is what you are missing.

**Comment by albertogasparin** [comment]
I'm also using the same values in my config. Are you also running chrome headless @mgamaHapyak?

**Comment by PawelWesolowski** [comment]
Just now I have had this problem after upgrading to High Sierra. Had to remove node_modules folder and rerun `npm install`

**Comment by albertogasparin** [comment]
I'm still on Sierra and I tried to start with a clean node_modules. No luck, still happening on several of our projects.

**Comment by marin42** [comment]
Did someone find a solution? I do have the same problem when running wdio on docker alpine.

**Comment by jansav** [comment]
Could this have something to do with this? 

https://github.com/giggio/node-chromedriver/issues/150

**Comment by worc** [comment]
i've updated to chromedriver 2.38.3 and i'm still seeing this same error message `ERROR: connect ECONNREFUSED 127.0.0.1:9515` and chrome browsers getting left open

**Comment by Eduard-iCH** [comment]
It's probably related to this: https://github.com/webdriverio/webdriverio/pull/2735
If you want to see which test is fall - do additional logging inside wdio.conf.js

```
  // Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
   afterTest: async function (test) {
      if (test.passed == false){
        console.log(`\n(pid: ${process.pid} / ${browser.desiredCapabilities.version}) <!> ${test.fullTitle} - FAILED <!> ` + ` (sid: ${browser.sessionId})`);

        if (test.err != null){
          console.log(test.err.stack);
        }
      }
   },
```

**Comment by yossarian21** [comment]
This is the same issue seen in node-chromedriver: https://github.com/giggio/node-chromedriver/issues/150

**Comment by worc** [comment]
the workaround seems like it's making up for really poor design. the errors should still print regardless of the screenshot issue.
